services:
    user_repository:
        class: AppBundle\Model\UserRepository
    stats_system:
        class: AppBundle\Service\StatsSystem
    marketing_system:
        class: AppBundle\Service\MarketingSystem
    email_changer:
        class: AppBundle\Service\EmailChanger
        arguments: [@doctrine.orm.entity_manager, @validator]
    doctrine_event.listener:
        class: AppBundle\EventListener\DoctrineEventListener
        arguments: [@service_container]
        tags:
            - { name: doctrine.event_listener, event: postUpdate, method: postUpdate }