AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
            fields: [username]
            message: "Username already in use"
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [email]
            message: "Email already in use"
    properties:
        username:
            - NotBlank:
                message: "Username should not be blank"
            - Length:
                min: 3
                max: 20
                minMessage: "Your login must be at least {{ limit }} characters long"
                maxMessage: "Your login cannot be longer than {{ limit }} characters"
            - Regex: 
                pattern: '/^[a-z0-9]+$/'
                message: "Username is invalid"
        email:
            - NotBlank: 
                message: "Email should not be blank"
            - Email:
        salt:
            - NotBlank:
        password:
            - NotBlank: