AppBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        username:
            type: string
            length: 20
            nullable: false
            unique: true
        email:
            type: string
            length: 255
            nullable: false
            unique: true
        name:
            type: string
            length: 100
        salt:
            type: string
            length: 100
            nullable: false
        password:
            type: string
            length: 100
            nullable: false